# Generated by Django 4.1.3 on 2022-11-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='image',
            field=models.ImageField(default='ffdds', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
